import random
from typing import Dict, Tuple, Optional

class Trainer:
    '''
    This class is responsible for the logic of training modes with filtered or unfiltered symbols to be considered in training (for example: only Hiragana, only Katakana, or all symbols).
    
    Attributes:
        symbol_pool (dict): Represents the pool of symbols being considered in the instance (example: it could be only Hiragana symbols, only Katakana symbols, or all combined).
        current_symbol: Represents the current random symbol.
        
    '''
    
    def __init__(self, symbol_pool: Dict[str, str]):
        '''
        __init__() Initializes the Trainer object with symbol_pool and initializes self.current_symbol.
        
        :param symbol_pool: Represents the pool of symbols being considered in the instance (example: it could be only Hiragana symbols, only Katakana symbols, or all combined).
        '''
        self.symbol_pool = symbol_pool
        self.current_symbol: Optional[Tuple[str, str]] = None
    
    def get_random_symbol(self) -> Tuple[str, str]:
        '''
        Randomly generates a symbol (more technically, generates a tuple with the symbol and its respective romaji) updating the state of self.current_symbol for consistency.
        
        :return: Returns the current_symbol (a tuple of the randomly generated symbol and romaji).
        :rtype: tuple
        '''
        if not self.symbol_pool:
            raise ValueError("symbol_pool is empty")
        
        self.current_symbol = random.choice(list(self.symbol_pool.items()))
        return self.current_symbol
    
    def is_romaji_equal_current(self, user_input_romaji: str) -> bool:
        '''
        is_romaji_equal_current() compares a romaji entered by the user (user_input_romaji) with the current romaji status of the Trainer class already generated (current_symbol). It also validates whether the entered romaji is not empty and whether the current romaji of the class has already been generated by get_random_symbol() first. 
        
        :param user_input_romaji: Romaji entered by the user through the interface.
        :type user_input_romaji: str
        :return: Returns True if the romaji entered by the user is equal to the romaji generated by the Trainer class. False if they are different.
        :rtype: bool
        '''
        if not user_input_romaji:
            raise ValueError("The romaji field entered by the user is empty.")
        if self.current_symbol is None:
            raise RuntimeError("No current symbol selected. Call get_random_symbol() first.")
        
        _, current_romaji = self.current_symbol
        return user_input_romaji.casefold() == current_romaji.casefold()